### PR TITLE
Translation of all static text on page

### PR DESCRIPTION
**Pull request by Ley21**
Hello developer of ffxiv-collect.
Maybe you remember I started to work on this a year ago. But because less free time I could not finish it until now.

I extract all englisch text from your page and translate them into german. You can see the result here (https://dev.ley21.de/)
Currently some friends are looking into the text to find typos or similar issues. If they are done it would be nice if you can merge it into your page. Maybe you will also find someone who can translate the text into fr/jp.

If you want talk in detail or I need to adjust something please contact me by discord (Ley21#0368).

Sry if I done something wrong from ruby/rails side, I'm not so familiar with this language.

### CODE REVIEW

**Comment by mattantonelli** [comment]
I think something went wrong with your pull request, as it's showing files that have not change as being changed. For example: `app/assets/stylesheets/application.scss` This is making the diff very difficult to sort through as it's showing both changes you have made and changes I made in my recent refactor.

**Comment by Ley21** [comment]
Maybe it is because of squashed commits. I will again check it in and finish then the pull request.

**Comment by Ley21** [comment]
sry miss cliecked for review. I will fix it in the next days

**Comment by mattantonelli** [comment]
From my initial review, I'm probably going to want to refactor at least half of this, so I think it would be best for you to just open a separate pull request with just the translations at a later date.

**Comment by Ley21** [comment]
Ok, then I will reopen a new pull request after your refactoring. If you may try to use already the t(....) method from i18n to move the english strings from the application, that would help me so I will afterwards translate it into german and help to for the rest.

**Pull request closed without merging**
