### PR TITLE
extend Lodestone to retrieve "private" data

### PR DESCRIPTION
**Pull request by electr0sheep**
Adds support for getting blue mage and orchestrion roll data

So, this isn't ready to be merged yet, but I wanted to provide an example of what I had in mind.

I think it would be cool to be able to retrieve "private" data in Lodestone, but I'm wondering if this has already been explored, and I'm just looking for feedback.

I'm not sure if this method is viable (making requests from one domain to another), but possibly you could just have the user paste in the raw html or something from Lodestone (ugly, to be sure, but at least not a manual process).

Also, it would be nice to be able to extract data that isn't in Lodestone as well (emotes, etc.)

Anyway, figured I'd just throw this out there before going down a crazy rabbit hole for nothing :)

### CODE REVIEW

**Comment by mattantonelli** [comment]
I appreciate the effort you've put into this, but I really can't support asking users to allow me to hijack their session like this. Sharing session cookies is a terribly unsafe web practice, and it also subjects me to some serious liability.

**Comment by electr0sheep** [comment]
Thanks for the feedback!

It sounds like this has already been explored. Since SE doesn't expose any form of an API (that I know of), I can't see how you could possibly get this private data elegantly.

I'll probably just write my own thing to get the data and check the boxes.

**Comment by mattantonelli** [comment]
> Since SE doesn't expose any form of an API (that I know of)

Not a darned one. It's why I have to keep making APIs for them. 😄

> I'll probably just write my own thing to get the data and check the boxes.

Just please code a delay into your script so it doesn't hammer my server. ❤️

**Comment by electr0sheep** [comment]
> Just please code a delay into your script so it doesn't hammer my server. ❤️

I will probably be the only one who uses it haha, not even sure how useful it will be, mostly just bored
Thanks for making this btw, I love tools that help me visualize my OCD 🤪

**Pull request closed without merging**
